added check for chaos provider that should be registered

diff --git a/.github/workflows/advanced-scenario.yml b/.github/workflows/advanced-scenario.yml
--- a/.github/workflows/advanced-scenario.yml
+++ b/.github/workflows/advanced-scenario.yml
@@ -72,63 +72,66 @@ jobs:
           echo "AGENTVMSIZE=${{ github.event.inputs.AGENTVMSIZE }}" >> $GITHUB_ENV
           echo "NODEPOOLS=${{ github.event.inputs.NODEPOOLS }}" >> $GITHUB_ENV
 
-      # Enable Chaos Studio on your AKS cluster
-      - name: Test with pwsh shell after setting env values and az login
+      - name: Check Microsoft.Chaos Provider or fail
+        run: |
+          provider=$(az provider list --query "[?namespace=='Microsoft.Chaos'].registrationState" -o tsv)
+          if [ "$provider" != "Registered" ]; then
+            echo "Error: Microsoft.Chaos provider is not registered."
+            exit 1
+          fi
+          echo "Microsoft.Chaos provider is registered."
+
+      # Deploy Bicep file Kubernetes service
+      - name: Deploy Bicep file Kubernetes service
+        id: Kubernetes
+        uses: azure/arm-deploy@v1
+        with:
+          scope: resourcegroup
+          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
+          resourceGroupName: ${{ secrets.AZURE_RG }}
+          template: ./Bicep/AKS/mainAKS.bicep
+          parameters: name="${{ env.KUBERNETESSERVICENAME }}" agentVMSize="${{ env.AGENTVMSIZE }}" agentCount="${{ env.NODEPOOLS }}"
+          failOnStdErr: false
+
+      # Kubectl tool installer
+      - name: Kubectl tool installer
+        uses: Azure/setup-kubectl@v2.1
+
+      # Deploy Nginx Reverse Proxy service to Kubernetes
+      - name: Deploy Nginx Reverse Proxy service to Kubernetes
+        run: |
+          az aks get-credentials -n "${{ env.KUBERNETESSERVICENAME }}" -g "${{ secrets.AZURE_RG }}"
+          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
+          helm repo update
+          helm upgrade nginx ingress-nginx/ingress-nginx --install
+
+      # Sleep
+      - name: Sleep for 30 seconds
         shell: pwsh
         run: |
-          az account show
+          sleep 30
 
-      # # Deploy Bicep file Kubernetes service
-      # - name: Deploy Bicep file Kubernetes service
-      #   id: Kubernetes
-      #   uses: azure/arm-deploy@v1
-      #   with:
-      #     scope: resourcegroup
-      #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
-      #     resourceGroupName: ${{ secrets.AZURE_RG }}
-      #     template: ./Bicep/AKS/mainAKS.bicep
-      #     parameters: name="${{ env.KUBERNETESSERVICENAME }}" agentVMSize="${{ env.AGENTVMSIZE }}" agentCount="${{ env.NODEPOOLS }}"
-      #     failOnStdErr: false
+      # Deploy Application with helm to Kubernetes service
+      - name: Deploy Application with helm to Kubernetes service
+        run: |
+          cd src/advanced-scenario/helm
+          RELEASE_NAME_LOWERCASE=$(echo ${{ env.APPNAME }} | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')
+          helm upgrade $RELEASE_NAME_LOWERCASE . --install 
+          echo "CLUSTERIP=$(kubectl get service "nginx-ingress-nginx-controller" -n default -o jsonpath="{.status.loadBalancer.ingress[0].ip}")" >> $GITHUB_ENV
 
-      # # Kubectl tool installer
-      # - name: Kubectl tool installer
-      #   uses: Azure/setup-kubectl@v2.1
+      # Deploy Prometheus service to Kubernetes
+      - name: Deploy Prometheus service to Kubernetes
+        run: |
+          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
+          helm repo update
+          helm upgrade --install prometheus-stack prometheus-community/kube-prometheus-stack --values src/advanced-scenario/prometheus.values.demo.yaml --wait --atomic --timeout 600s --set grafana.adminPassword="${{ secrets.GRAFANA_ADMIN_PASSWORD }}" --namespace "prometheus" --create-namespace
 
-      # # Deploy Nginx Reverse Proxy service to Kubernetes
-      # - name: Deploy Nginx Reverse Proxy service to Kubernetes
-      #   run: |
-      #     az aks get-credentials -n "${{ env.KUBERNETESSERVICENAME }}" -g "${{ secrets.AZURE_RG }}"
-      #     helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
-      #     helm repo update
-      #     helm upgrade nginx ingress-nginx/ingress-nginx --install
-
-      # # Sleep
-      # - name: Sleep for 30 seconds
-      #   shell: pwsh
-      #   run: |
-      #     sleep 30
-
-      # # Deploy Application with helm to Kubernetes service
-      # - name: Deploy Application with helm to Kubernetes service
-      #   run: |
-      #     cd src/advanced-scenario/helm
-      #     RELEASE_NAME_LOWERCASE=$(echo ${{ env.APPNAME }} | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')
-      #     helm upgrade $RELEASE_NAME_LOWERCASE . --install 
-      #     echo "CLUSTERIP=$(kubectl get service "nginx-ingress-nginx-controller" -n default -o jsonpath="{.status.loadBalancer.ingress[0].ip}")" >> $GITHUB_ENV
-
-      # # Deploy Prometheus service to Kubernetes
-      # - name: Deploy Prometheus service to Kubernetes
-      #   run: |
-      #     helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
-      #     helm repo update
-      #     helm upgrade --install prometheus-stack prometheus-community/kube-prometheus-stack --values src/advanced-scenario/prometheus.values.demo.yaml --wait --atomic --timeout 600s --set grafana.adminPassword="${{ secrets.GRAFANA_ADMIN_PASSWORD }}" --namespace "prometheus" --create-namespace
-
-      # # Set up Chaos Mesh on your AKS cluster
-      # - name: Set up Chaos Mesh on AKS cluster
-      #   run: |
-      #     helm repo add chaos-mesh https://charts.chaos-mesh.org
-      #     helm repo update
-      #     helm upgrade --install chaos-mesh chaos-mesh/chaos-mesh --set chaosDaemon.runtime=containerd --set chaosDaemon.socketPath=/run/containerd/containerd.sock --namespace "chaos-testing" --create-namespace
+      # Set up Chaos Mesh on your AKS cluster
+      - name: Set up Chaos Mesh on AKS cluster
+        run: |
+          helm repo add chaos-mesh https://charts.chaos-mesh.org
+          helm repo update
+          helm upgrade --install chaos-mesh chaos-mesh/chaos-mesh --set chaosDaemon.runtime=containerd --set chaosDaemon.socketPath=/run/containerd/containerd.sock --namespace "chaos-testing" --create-namespace
 
       # Enable Chaos Studio on your AKS cluster
       - name: Enable Chaos Studio on AKS cluster
